author: "kubiyamg@gmail.com"
version: 3
type: "conversation"
name: "Delete Argo Application"
steps:
  - type: "action"
    id: "get_all_apps"
    action:
      name: "get_all_apps"
      store: "argo"
      runner: "<your runner>"
      async: false
      parameters: {}
  - type: "jq"
    id: "parse_apps"
    jq: ".get_all_apps.items[].metadata.name"
  - type: "input"
    value_type: "enum"
    id: "select_app"
    prompt: "Which application would you like to delete?"
    possible_values: "${parse_apps}"
  - type: "input"
    value_type: "boolean"
    id: "confirm_deletion"
    prompt: "Are you sure you want to delete ${select_app}?"
  - type: "condition"
    id: "delete_condition"
    if:
      arg: "${confirm_deletion}"
      is: "equals"
      arg2: "true"
      then:
        - type: "action"
          id: "delete_app"
          action:
            name: "delete_app"
            store: "argo"
            runner: "<your runner>"
            async: false
            parameters:
              app_name: "${select_app}"
        - type: "message"
          id: "successful_delete"
          label: ""
          prompt: "We have successfully deleted Application: ${select_app}."
        - type: "exit"
          id: "true_exit"
      else:
        - type: "message"
          id: "cancel_deletion_message"
          prompt: "Ok, I have canceled the deletion of ${select_app}. Let me know if I can be of any further assistance."
        - type: "exit"
          id: "false_exit"
