version: 3
type: conversation
name: "kubernetes_delete_job"
steps:
  - id: k8s_namespaces
    type: action
    action:
      runner: "demo"
      store: kubernetes
      name: "list_namespace"
      parameters: {}
  - id: selected_namespace
    type: input
    value_type: enum
    possible_values: ${k8s_namespaces}
    prompt: "Select the namespace of the job you want to delete"
  - id: k8s_jobs
    type: action
    action:
      runner: "demo"
      store: kubernetes
      name: "list_namespaced_jobs"
      parameters:
        namespace: ${selected_namespace}
  - id: selected_job
    type: input
    value_type: enum
    possible_values: ${k8s_jobs}
    prompt: "Select the job you want to delete"
  - id: validate
    type: input
    value_type: boolean
    prompt: '⚠️ Job *${selected_job}* will be deleted in namespace *${selected_namespace}*. Do you want to continue?'
  - id: condition
    type: condition
    if:
      arg: ${validate}
      is: equals
      arg2: "true"
      then:
        - id: notify
          type: message
          prompt: |
            🔄 Deleting job *${selected_job}* in namespace *${selected_namespace}*...
        - id: delete
          type: action
          action:
            runner: "demo"
            store: kubernetes
            name: "delete_namespaced_job"
            parameters:
              name: ${selected_job}
              namespace: ${selected_namespace}
        - id: print_job
          type: message
          prompt: |
            ✅ *Done!*
            Job *${selected_job}* deleted in namespace *${selected_namespace}*!
      else:
        - id: cancel
          type: message
          prompt: |
            ❌ *Cancelled!*
            Job *${selected_job}* deletion cancelled!